<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icons\Contact\Github.png" />
    <None Remove="Resources\Icons\Contact\Gmail.png" />
    <None Remove="Resources\Icons\Contact\Instagram.png" />
    <None Remove="Resources\Icons\Contact\X.png" />
    <None Remove="Resources\Icons\Technologies\Csharp.png" />
    <None Remove="Resources\Icons\Technologies\DotNet.png" />
    <None Remove="Resources\Icons\Technologies\Figma.png" />
    <None Remove="Resources\Icons\Technologies\FontAwesome.png" />
    <None Remove="Resources\Icons\Technologies\WPF.png" />
    <None Remove="Resources\Images\Developer\Official\Amin.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Images\Countries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="LiveCharts" Version="0.9.7" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\Contact\Github.png" />
    <Resource Include="Resources\Icons\Contact\Gmail.png" />
    <Resource Include="Resources\Icons\Contact\Instagram.png" />
    <Resource Include="Resources\Icons\Contact\X.png" />
    <Resource Include="Resources\Icons\Technologies\Csharp.png" />
    <Resource Include="Resources\Icons\Technologies\DotNet.png" />
    <Resource Include="Resources\Icons\Technologies\Figma.png" />
    <Resource Include="Resources\Icons\Technologies\FontAwesome.png" />
    <Resource Include="Resources\Icons\Technologies\WPF.png" />
    <Resource Include="Resources\Images\Developer\Fantasy\DevBlue.png" />
    <Resource Include="Resources\Images\Developer\Fantasy\DevGreen.png" />
    <Resource Include="Resources\Images\Developer\Fantasy\DevMagenta.png" />
    <Resource Include="Resources\Images\Developer\Fantasy\DevOrange.png" />
    <Resource Include="Resources\Images\Developer\Fantasy\DevPink.png" />
    <Resource Include="Resources\Images\Developer\Fantasy\DevRed.png" />
    <Resource Include="Resources\Images\Developer\Official\Amin.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Localization\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Localization\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
