<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>TVSettingsIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Countries\China.png" />
    <None Remove="Images\Countries\Germany.png" />
    <None Remove="Images\Countries\Iran.png" />
    <None Remove="Images\Countries\Spain.png" />
    <None Remove="Images\Countries\USA.png" />
    <None Remove="Images\Developer\DevBlue.png" />
    <None Remove="Images\Developer\DevGreen.png" />
    <None Remove="Images\Developer\DevMagenta.png" />
    <None Remove="Images\Developer\DevOrange.png" />
    <None Remove="Images\Developer\DevPink.png" />
    <None Remove="Images\Developer\DevRed.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="TVSettingsIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts" Version="0.9.7" />
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="MahApps.Metro.IconPacks.Core" Version="6.2.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Countries\China.png" />
    <Resource Include="Images\Countries\Germany.png" />
    <Resource Include="Images\Countries\Iran.png" />
    <Resource Include="Images\Countries\Spain.png" />
    <Resource Include="Images\Countries\USA.png" />
    <Resource Include="Images\Developer\DevBlue.png" />
    <Resource Include="Images\Developer\DevGreen.png" />
    <Resource Include="Images\Developer\DevMagenta.png" />
    <Resource Include="Images\Developer\DevOrange.png" />
    <Resource Include="Images\Developer\DevPink.png" />
    <Resource Include="Images\Developer\DevRed.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

</Project>
